In [1]:
import zipfile
import pandas as pd

from io import BytesIO

with zipfile.ZipFile("simulation_config.zip", "r") as zf:
    with zf.open("stays.parquet") as f:
        stays_file = BytesIO(f.read())
        occupancy_file = BytesIO(zf.read("occupancy.parquet"))

stays_df = pd.read_parquet(stays_file)
occupancy_df = pd.read_parquet(occupancy_file)

In [2]:
stays_df

,Age,Admission,Discharge,ReAdmission,ReAdmissionDischarge,FirstPosCollected,Acquisition
0,88,2021-12-01 07:22:04.672,2021-12-01 12:08:15.104,2021-12-13 13:37:28.576,2021-12-13 16:45:20.768,2021-12-01 07:35:11.104,Community-Onset Community-Associated
1,48,2021-12-01 12:47:34.400,2021-12-07 19:29:21.408,2021-12-13 16:34:25.408,2021-12-19 09:26:05.056,2021-12-01 16:50:03.392,Community-Onset Community-Associated
2,39,2021-12-01 16:34:45.888,2021-12-04 18:59:57.056,NaT,NaT,2021-12-01 17:42:29.120,Community-Onset Community-Associated
3,72,2021-12-01 20:00:06.656,2021-12-23 14:39:05.216,NaT,NaT,2021-12-01 21:23:07.392,Community-Onset Community-Associated
4,73,2021-12-01 13:40:00.128,2021-12-02 20:04:05.248,NaT,NaT,2021-12-02 06:37:59.680,Community-Onset Community-Associated
...,...,...,...,...,...,...,...
5524,75,2024-05-31 11:29:12.192,2024-06-02 16:34:15.168,NaT,NaT,2024-05-31 17:20:54.784,Community-Onset Community-Associated
5525,56,2024-03-17 23:35:30.560,NaT,NaT,NaT,2024-06-01 02:37:58.144,Hospital-Onset Healthcare-Associated
5526,80,2024-06-03 11:10:32.960,2024-06-13 18:34:27.200,NaT,NaT,2024-06-03 11:38:56.896,Community-Onset Community-Associated
5527,88,2024-06-03 17:39:23.776,2024-06-12 11:59:26.720,NaT,NaT,2024-06-03 17:52:30.208,Community-Onset Community-Associated
5528,59,2024-06-03 19:13:19.872,2024-06-05 18:31:02.400,NaT,NaT,2024-06-03 18:51:29.152,Community-Onset Community-Associated

In [3]:
occupancy_df

           date  critical  noncritical
0    2020-03-12         0            1
1    2020-03-13         0            1
2    2020-03-14         0            1
3    2020-03-15         0            2
4    2020-03-16         0            4
...         ...       ...          ...
1683 2024-10-20         2           69
1684 2024-10-21         2           72
1685 2024-10-22         2           71
1686 2024-10-23         1           68
1687 2024-10-24         1           70

[1688 rows x 3 columns]

In [4]:
stays_df.dtypes

Age                              int64
Admission               datetime64[ns]
Discharge               datetime64[ns]
ReAdmission             datetime64[ns]
ReAdmissionDischarge    datetime64[ns]
FirstPosCollected       datetime64[ns]
Acquisition                     object
dtype: object

In [5]:
occupancy_df.dtypes

date           datetime64[ns]
critical                int64
noncritical             int64
dtype: object